apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosampleapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gosampleapp
  template:
    metadata:
      labels:
        app: gosampleapp
    spec:
      containers:
      - name: gosampleapp
        image: image: kisinma/repo-harness:latest
        ports:
        - containerPort: 8080
